### ISSUE TITLE
parser error

### ISSUE THREAD

**Issue by docccdev** [zemlanin/schwartzman#1]
`Module build failed: SyntaxError: Line 2: expected [_a-zA-Z0-9], ".", [_a-zA-Z0-9], "{{/"`
`{{# onClick }}onClick={{ onClick }}{{/ onClick }}`

**Comment by zemlanin** [comment]
Yeah, you cannot have nested mustache nodes if whole attribute is inside condition

As a workaround, set `data-*` attribute and bind event handlers externally, via `addEventListener()`

```js
Array.prototype.forEach.call(
  node.querySelectorAll('[data-onclick-trigger="whatever"]'),
  (n) => n.addEventListener('click', whateverFn)
)
```
