### ISSUE TITLE
problem with class

### ISSUE THREAD

**Issue by docccdev** [zemlanin/schwartzman#2]
https://schwartzman.anton.codes/?tmpl=%3Cdiv%20class%3D%22%7B%7B%23suffix%7D%7Dc_%7B%7Bsuffix%7D%7D%7B%7B%2Fsuffix%7D%7D%22%3Eclass%20should%20be%20equal%20c_x%3C%2Fdiv%3E&props=%7B%22suffix%22%3A%20%22x%22%7D

**Comment by zemlanin** [comment]
fixed in 301768244ec16e48e1d7cfc797ac460652096e81
