### ISSUE TITLE
Problem with strings

### ISSUE THREAD

**Issue by lNevermindl** [zemlanin/schwartzman#3]
'null' is rendered when conditional section is placed inside of a string and the condition is False.
http://schwartzman.anton.codes/?tmpl=%3Cspan%20class%3D%27x%20%7B%7B%5E%20y%20%7D%7Dy%7B%7B%2F%20y%20%7D%7D%27%3E%0A%20%20class%20should%20be%20%27x%27%0A%3C%2Fspan%3E&props=%7By%3A%201%7D

**Comment by zemlanin** [comment]
Fixed in 0.7.4
